### ISSUE TITLE
NullreferenceException in GameControl.cs

### ISSUE THREAD

**Issue by Kyzure** [TruckDefenseInstitute/Convoy#6]
![image](https://user-images.githubusercontent.com/36699735/74080177-03e59880-4a7c-11ea-8ceb-6488d3acea14.png)

Happens when clicking outside any non-nav-mesh-baked place in GameControl.cs

**Comment by ChengGeng97** [comment]
Problem fixed:
https://github.com/TruckDefenseInstitute/Convoy/commit/2a2a33d67e2c0056470afde2834da0bded9d5565
